In [1]:
import cvxpy as cp
import numpy as np

In [2]:
def check_solution(x, y, A, rhs):
    for A_, rhs_ in zip(A, rhs):
        if A_(x, y) > rhs_:
            print(f"Constraint is violated with value {A_(x, y)} > {rhs_}.")
        else:
            print(f"Constraint is satisfied with value {A_(x, y)} <= {rhs_}.")

# Linear Programming

In [3]:
# Define the decision variables
x = cp.Variable(nonneg=True)  # x >= 0
y = cp.Variable(nonneg=True)  # y >= 0

In [4]:
# z = cp.Variable(5, nonneg=True)

In [5]:
# 5*x, x**2, -cp.sqrt(x), x**2/x, cp.max(z), cp.mean(z)

In [6]:
# Define the decision variables
x = cp.Variable(nonneg=True)  # x >= 0
y = cp.Variable(nonneg=True)  # y >= 0

# Define the objective function
objective = cp.Maximize(20*x + 25*y)

# Define the constraints
constraints = [
    2*x + 3*y <= 30,
    3*x + 1*y <= 20,
]

# Define and solve the problem
problem = cp.Problem(objective, constraints)
problem.solve()

# Print the optimal solution and optimal value
print("Optimal solution: x =", x.value, ", y =", y.value)
print("Optimal value:", problem.value)

Optimal solution: x = 4.2857142829410995 , y = 7.142857144661429
Optimal value: 264.2857142753577


In [7]:
# Define the constraints
A = [
    lambda x, y: 2*x + 3*y,
    lambda x, y: 3*x + 1*y,
]

rhs = [
    30,
    20,
]

check_solution(x.value, y.value, A, rhs)

Constraint is satisfied with value 29.99999999986649 <= 30.
Constraint is satisfied with value 19.999999993484728 <= 20.


In [8]:
constraints[0].dual_value, constraints[1].dual_value

(7.857142857545608, 1.4285714288297986)

In [9]:
x.value, y.value

(np.float64(4.2857142829410995), np.float64(7.142857144661429))

# Integer Programming

In [10]:
# Define the decision variables
x = cp.Variable(integer=True)
y = cp.Variable(integer=True)

# Define the objective function
objective = cp.Maximize(20*x + 25*y)

# Define the constraints
constraints = [
    2*x + 3*y <= 30,
    3*x + 1*y <= 20,
    x >= 0,  # x >= 0
    y >= 0,  # y >= 0
]

# Define and solve the problem
problem = cp.Problem(objective, constraints)
problem.solve()

# Print the optimal solution and optimal value
print("Optimal solution: x =", x.value, ", y =", y.value)
print("Optimal value:", problem.value)

Optimal solution: x = 3.0 , y = 8.0
Optimal value: 260.0


In [11]:
# Define the constraints
A = [
    lambda x, y: 2*x + 3*y,
    lambda x, y: 3*x + 1*y,
]

rhs = [
    30,
    20,
]

check_solution(x.value, y.value, A, rhs)

Constraint is satisfied with value 30.0 <= 30.
Constraint is satisfied with value 17.0 <= 20.


In [12]:
# NOTE: cvxpy can't return dual_value in MIP (integer)
constraints[0].dual_value, constraints[1].dual_value

(None, None)

In [13]:
x.value, y.value

(array(3.), array(8.))

# Vector Form

In [14]:
# Define the decision variables
x = cp.Variable((2, 1), integer=True)
x

Variable((2, 1), var147, integer=True)

In [15]:
c = np.array([[20, 25]])
c, c.shape

(array([[20, 25]]), (1, 2))

In [16]:
# Define the objective function
objective = cp.Maximize(c @ x)
objective

Maximize(Expression(AFFINE, UNKNOWN, (1, 1)))

In [17]:
A = np.array([
    [2, 3],
    [3, 1],
])
b = np.array(
    [
        [30],
        [20]
    ]
)
A @ x, b, A @ x <= b

(Expression(AFFINE, UNKNOWN, (2, 1)),
 array([[30],
        [20]]),
 Inequality(Expression(AFFINE, UNKNOWN, (2, 1))))

In [18]:
# Define the constraints
constraints = [
    A @ x <= b,
    x >= 0,  # x >= 0
]

# Define and solve the problem
problem = cp.Problem(objective, constraints)
problem.solve()

# Print the optimal solution and optimal value
print("Optimal solution: x =", x.value, ", y =", y.value)
print("Optimal value:", problem.value)

Optimal solution: x = [[3.]
 [8.]] , y = 8.0
Optimal value: 260.0


In [19]:
x.value

array([[3.],
       [8.]])

In [20]:
constraints[0].dual_value